/* 
Name: Riki Choi
Student ID: 103475494
*/


/* 
ERD to Relational Schema

SUBJECT(SUBJCODE, DESCRIPTION)
PRIMARY KEY(SUBJCODE)

TEACHER(STAFFID, SURNAME, GIVENNAME)
PRIMARY KEY(STAFFID)

STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
PRIMARY KEY(STUDENTID)

SUBJECTOFFERING(SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
PRIMARY KEY(SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY(SUBJCODE) REFERENCES (SUBJECT)
FOREIGN KEY(STAFFID) REFERENCES TEACHER

ENROLMENT(STUDENTID, SUBJCODE, YEAR, SEMESTER, DATEENROLLED, GRADE)
PRIMARY KEY(STUDENTID, SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY(STUDENTID) REFERENCES STUDENT
FOREIGN KEY(SUBJCODE, YEAR, SEMESTER) REFERENCES SUBJECTOFFERING
*/
